### ISSUE TITLE
Error when calling `join()`

### ISSUE THREAD

**Issue by the-drunk-coder** [chemicstry/wasm_thread#11]
Hi, I tried to build a little scheduler using wasm_thread, based on the simple example (build with the provided build.sh script)

When I call `join()` on the JoinHandle, I get the following error in the console: 

```
Uncaught RuntimeError: Atomics.wait cannot be called in this context
    at std::thread::park::h593d412d90d62fe8 (simple_bg.wasm:0xa15d)
    at std::thread::local::LocalKey<T>::with::h7c7778a2607becf9 (simple_bg.wasm:0xb690)
    at futures_executor::local_pool::block_on::hf38892d64f63bc2a (simple_bg.wasm:0xc0e9)
    at wasm_thread::JoinHandle<T>::join::hb8eb16f7d78b7dfe (simple_bg.wasm:0xc237)
    at stop_scheduler (simple_bg.wasm:0x7531)
    at WebAudioSwitch.<anonymous> (simple.html:21:10)
    at WebAudioSwitch.sendEvent (webaudio-controls.js:159:12)
    at WebAudioSwitch.pointerdown (webaudio-controls.js:1046:14)
$std::thread::park::h593d412d90d62fe8 @ simple_bg.wasm:0xa15d
$std::thread::local::LocalKey<T>::with::h7c7778a2607becf9 @ simple_bg.wasm:0xb690
$futures_executor::local_pool::block_on::hf38892d64f63bc2a @ simple_bg.wasm:0xc0e9
$wasm_thread::JoinHandle<T>::join::hb8eb16f7d78b7dfe @ simple_bg.wasm:0xc237
$stop_scheduler @ simple_bg.wasm:0x7531
(anonymous) @ simple.html:21
sendEvent @ webaudio-controls.js:159
pointerdown @ webaudio-controls.js:1046

```

Best,
N

**Comment by the-drunk-coder** [comment]
Ah right, yes ... sorry, must have missed that. Thanks for the quick reply !
